package com.findatex.validator.validation;

import com.findatex.validator.domain.TptFile;
import com.findatex.validator.ingest.TptFileLoader;
import com.findatex.validator.report.QualityReport;
import com.findatex.validator.report.QualityScorer;
import com.findatex.validator.spec.SpecCatalog;
import com.findatex.validator.spec.SpecLoader;
import com.findatex.validator.template.api.ProfileKey;
import com.findatex.validator.template.tpt.TptProfiles;
import com.findatex.validator.template.tpt.TptRuleSet;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies multi-fund TPT files: each fund must be validated independently and
 * every finding must carry the portfolio context of the fund it originated
 * from. Disabled if {@code samples/tpt/12_multi_fund_clean.xlsx} or
 * {@code samples/tpt/13_multi_fund_with_errors.xlsx} are missing — both are
 * regenerated by {@code tools/build_examples.py}.
 */
@EnabledIf("samplesPresent")
class MultiFundTest {

    private static final SpecCatalog CATALOG = SpecLoader.loadBundled();
    private static final Set<ProfileKey> ALL = new java.util.HashSet<>(java.util.Arrays.asList(
            TptProfiles.SOLVENCY_II, TptProfiles.IORP_EIOPA_ECB,
            TptProfiles.NW_675, TptProfiles.SST));

    static boolean samplesPresent() {
        Path dir = samplesDir();
        return dir != null
            && Files.exists(dir.resolve("12_multi_fund_clean.xlsx"))
            && Files.exists(dir.resolve("13_multi_fund_with_errors.xlsx"));
    }

    /** Walk up from cwd until {@code samples/tpt} appears — works whether
     *  surefire runs from the repo root or from the {@code core/} module. */
    private static Path samplesDir() {
        Path p = Paths.get("").toAbsolutePath();
        for (int i = 0; i < 5 && p != null; i++) {
            Path candidate = p.resolve("samples").resolve("tpt");
            if (Files.isDirectory(candidate)) return candidate;
            p = p.getParent();
        }
        return null;
    }

    @Test
    void multiFundCleanProducesNoErrors() throws Exception {
        QualityReport r = run("12_multi_fund_clean.xlsx");

        long dataErrors = r.findings().stream()
                .filter(f -> f.severity() == Severity.ERROR)
                .filter(f -> f.ruleId().startsWith("FORMAT/")
                          || f.ruleId().startsWith("ISIN/")
                          || f.ruleId().startsWith("LEI/")
                          || f.ruleId().startsWith("XF-"))
                .count();
        assertThat(dataErrors).as("clean multi-fund must have zero data errors").isZero();

        // Each fund must have its own findings carrying its portfolio id —
        // proves the FundGrouper / FindingEnricher refactor works.
        assertThat(r.findings()).extracting(f -> f.context().portfolioId())
                .contains("FR0010000001", "DE0010000002", "LU0010000003");

        // Per-fund scoring is populated when the file holds more than one fund.
        assertThat(r.perFundScores()).hasSize(3);
    }

    @Test
    void multiFundErrorsAttributedToCorrectFund() throws Exception {
        QualityReport r = run("13_multi_fund_with_errors.xlsx");

        // XF-04 fires for Fund B only.
        List<Finding> weight = r.findings().stream()
                .filter(f -> "XF-04/POSITION_WEIGHT_SUM".equals(f.ruleId()))
                .toList();
        assertThat(weight).hasSize(1);
        assertThat(weight.get(0).context().portfolioId()).isEqualTo("DE0010000002");

        // ISIN-checksum ERROR fires only on Fund B's first position.
        List<Finding> isin = r.findings().stream()
                .filter(f -> f.ruleId().startsWith("ISIN/"))
                .filter(f -> f.severity() == Severity.ERROR)
                .toList();
        assertThat(isin).isNotEmpty();
        assertThat(isin).extracting(f -> f.context().portfolioId())
                .containsOnly("DE0010000002");

        // Missing NAV (field 5) presence error fires only for Fund C.
        List<Finding> presence5 = r.findings().stream()
                .filter(f -> f.ruleId().startsWith("PRESENCE/5/"))
                .filter(f -> f.severity() == Severity.ERROR)
                .toList();
        assertThat(presence5).isNotEmpty();
        assertThat(presence5).extracting(f -> f.context().portfolioId())
                .containsOnly("LU0010000003");

        // Fund A (FR) carries no FORMAT/ISIN/LEI/XF- ERROR findings.
        assertThat(r.findings()).filteredOn(f ->
                "FR0010000001".equals(f.context().portfolioId())
                && f.severity() == Severity.ERROR
                && (f.ruleId().startsWith("FORMAT/")
                    || f.ruleId().startsWith("ISIN/")
                    || f.ruleId().startsWith("LEI/")
                    || f.ruleId().startsWith("XF-")))
            .isEmpty();
    }

    private QualityReport run(String filename) throws Exception {
        Path p = samplesDir().resolve(filename);
        assertThat(Files.exists(p)).as("missing sample %s", p).isTrue();
        TptFile file = new TptFileLoader(CATALOG).load(p);
        List<Finding> findings = new ValidationEngine(CATALOG, new TptRuleSet()).validate(file, ALL);
        return new QualityScorer(CATALOG).score(file, ALL, findings);
    }
}
