package com.findatex.validator.validation;

import com.findatex.validator.domain.TptFile;
import com.findatex.validator.ingest.TptFileLoader;
import com.findatex.validator.report.QualityReport;
import com.findatex.validator.report.QualityScorer;
import com.findatex.validator.report.ScoreCategory;
import com.findatex.validator.template.api.ProfileKey;
import com.findatex.validator.template.tpt.TptProfiles;
import com.findatex.validator.spec.SpecCatalog;
import com.findatex.validator.spec.SpecLoader;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Smoke-tests every file under {@code samples/tpt/} (project root) to confirm the
 * intended validation outcome. Disabled automatically if the directory is
 * missing — {@code samples/tpt/} is generated by {@code tools/build_examples.py}
 * and tracked in git.
 */
@EnabledIf("samplesPresent")
class ExampleSamplesTest {

    private static final SpecCatalog CATALOG = SpecLoader.loadBundled();
    private static final Set<ProfileKey> ALL = new java.util.HashSet<>(java.util.Arrays.asList(TptProfiles.SOLVENCY_II, TptProfiles.IORP_EIOPA_ECB, TptProfiles.NW_675, TptProfiles.SST));

    static boolean samplesPresent() {
        return Files.isDirectory(samplesDir());
    }

    private static Path samplesDir() {
        return Paths.get("").toAbsolutePath().resolve("samples").resolve("tpt");
    }

    @Test
    void cleanFileHasNoDataErrors() throws Exception {
        QualityReport r = run("01_clean.xlsx");
        // A minimal clean sample only fills ~40 of the 142 spec fields, so it
        // legitimately incurs PRESENCE warnings/errors for unused M-fields under
        // the IORP/NW 675 profiles. The semantic of "clean" is: every value
        // that IS present is well-formed and consistent — no FORMAT, ISIN/LEI
        // checksum or cross-field errors.
        long dataErrors = r.findings().stream()
                .filter(f -> f.severity() == Severity.ERROR)
                .filter(f -> f.ruleId().startsWith("FORMAT/")
                          || f.ruleId().startsWith("ISIN/")
                          || f.ruleId().startsWith("LEI/")
                          || f.ruleId().startsWith("XF-"))
                .count();
        assertThat(dataErrors).as("01_clean must have zero data errors").isZero();
        assertThat(r.scores().get(ScoreCategory.FORMAT_CONFORMANCE))
                .as("01_clean format conformance").isEqualTo(1.0);
    }

    @Test
    void missingMandatoryFlagged() throws Exception {
        QualityReport r = run("02_missing_mandatory.csv");
        long presence = r.findings().stream()
                .filter(f -> f.severity() == Severity.ERROR)
                .filter(f -> f.ruleId().startsWith("PRESENCE/"))
                .count();
        assertThat(presence).isGreaterThanOrEqualTo(3);
    }

    @Test
    void badFormatsFlagged() throws Exception {
        QualityReport r = run("03_bad_formats.xlsx");
        boolean badCcy   = hasFinding(r, "FORMAT/21");
        boolean badCtry  = hasFinding(r, "FORMAT/52");
        boolean badDate  = hasFinding(r, "FORMAT/6");
        assertThat(badCcy).as("invalid currency caught").isTrue();
        assertThat(badCtry).as("invalid country caught").isTrue();
        assertThat(badDate).as("invalid date caught").isTrue();
    }

    @Test
    void badClosedListValuesFlagged() throws Exception {
        QualityReport r = run("04_bad_closed_lists.xlsx");
        boolean badCodSys = hasFinding(r, "FORMAT/15");      // 42
        boolean badFreq   = hasFinding(r, "XF-08/COUPON_FREQUENCY");
        boolean badRedem  = hasFinding(r, "FORMAT/40");      // VeryWeirdRedemption
        assertThat(badCodSys).as("invalid codification system caught").isTrue();
        assertThat(badFreq).as("invalid coupon frequency caught").isTrue();
        assertThat(badRedem).as("invalid redemption type caught").isTrue();
    }

    @Test
    void badIsinChecksumFlagged() throws Exception {
        QualityReport r = run("05_bad_isin_checksum.xlsx");
        boolean isinFailed = r.findings().stream().anyMatch(f -> f.ruleId().startsWith("ISIN/"));
        assertThat(isinFailed).isTrue();
    }

    @Test
    void badLeiChecksumFlagged() throws Exception {
        QualityReport r = run("06_bad_lei_checksum.xlsx");
        boolean leiFailed = r.findings().stream().anyMatch(f -> f.ruleId().startsWith("LEI/"));
        assertThat(leiFailed).isTrue();
    }

    @Test
    void weightSumOutOfTolerance() throws Exception {
        QualityReport r = run("07_weights_dont_sum.xlsx");
        assertThat(hasFinding(r, "XF-04/POSITION_WEIGHT_SUM")).isTrue();
    }

    @Test
    void navMismatchAndCashRatio() throws Exception {
        QualityReport r = run("08_nav_mismatch.xlsx");
        assertThat(hasFinding(r, "XF-06/NAV_PRICE_SHARES")).isTrue();
        assertThat(hasFinding(r, "XF-05/CASH_PERCENTAGE")).isTrue();
    }

    @Test
    void interestRateInconsistencyFlagged() throws Exception {
        QualityReport r = run("09_interest_rate_inconsistent.xlsx");
        assertThat(hasFinding(r, "XF-10/INTEREST_RATE_TYPE")).isTrue();
    }

    @Test
    void dateOrderAndUnderlyingCicFlagged() throws Exception {
        QualityReport r = run("10_dates_and_derivatives.xlsx");
        assertThat(hasFinding(r, "XF-12/DATE_ORDER")).isTrue();
        assertThat(hasFinding(r, "XF-14/UNDERLYING_CIC")).isTrue();
    }

    private static boolean hasFinding(QualityReport r, String ruleId) {
        return r.findings().stream().anyMatch(f -> f.ruleId().equals(ruleId));
    }

    private QualityReport run(String filename) throws Exception {
        Path p = samplesDir().resolve(filename);
        assertThat(Files.exists(p)).as("missing sample %s", p).isTrue();
        TptFile file = new TptFileLoader(CATALOG).load(p);
        List<Finding> findings = new ValidationEngine(CATALOG).validate(file, ALL);
        return new QualityScorer(CATALOG).score(file, ALL, findings);
    }
}
