"""Generate the EET V1.1.3 sample fixtures into ``samples/eet/``.

Five files: clean baseline plus four broken variants targeting different
rule families (presence, format, SFDR Art-8 conditional, SFDR Art-9
conditional).
"""
from __future__ import annotations

from copy import deepcopy
from pathlib import Path

from findatex_sample_helpers import (
    ROOT, FieldRow, load_spec, value_for, write_scenarios,
)

OUT = ROOT / "samples" / "eet"
OUT.mkdir(parents=True, exist_ok=True)

MANIFEST, FIELDS = load_spec("EET", "V1.1.3")

# Header row = all M-flagged fields, plus the SFDR-conditional fields
# (NUM 28, 30, 31, 40, 41, 45, 48) so the XF scenarios have the columns
# they need.
M_NUMS = [r.num for r in FIELDS if r.flag == "M"]
EXTRA_NUMS = ["28", "30", "31", "40", "41", "45", "48"]
HEADER_NUMS = M_NUMS + [n for n in EXTRA_NUMS if n not in M_NUMS]

BY_NUM: dict[str, FieldRow] = {r.num: r for r in FIELDS}
HEADERS = [BY_NUM[n].path for n in HEADER_NUMS]


def clean_row() -> dict[str, str]:
    """Build one fully-populated EET row (M fields + SFDR Art-8 defaults)."""
    row = {n: "" for n in HEADER_NUMS}
    for n in M_NUMS:
        row[n] = value_for(BY_NUM[n].codif)
    # Make the row look like an Art-8 product so default Art-8 conditional
    # presence is satisfied — set NUM=27 to "8" and supply NUM=30/40/41.
    row["27"] = "8"
    row["30"] = "0.5"
    row["40"] = "Y"
    row["41"] = "0.3"
    return row


# ----- scenarios ----------------------------------------------------------

def s01_clean() -> list[dict[str, str]]:
    return [clean_row()]


def s02_missing_mandatory() -> list[dict[str, str]]:
    r = clean_row()
    # Blank five M fields so PRESENCE/* fires multiple times.
    for n in ["5", "7", "23", "25", "26"]:
        r[n] = ""
    return [r]


def s03_bad_formats() -> list[dict[str, str]]:
    r = clean_row()
    r["5"] = "31/12/2025 12:00"   # NUM=5 is ISO 8601 datetime → wrong format
    r["15"] = "2025-13-40"        # NUM=15 is ISO 8601 date → impossible date
    r["26"] = "EuroX"             # NUM=26 is ISO 4217 → not a 3-letter code
    r["7"] = "Maybe"              # NUM=7 is Y/N → invalid
    return [r]


def s04_sfdr_art8_no_min() -> list[dict[str, str]]:
    r = clean_row()
    r["27"] = "8"  # SFDR Art-8 product
    r["30"] = ""   # blank → triggers EET-XF-ART8-MIN-LT
    r["40"] = "Y"  # has sustainable investments
    r["41"] = ""   # blank → triggers EET-XF-ART8-MIN-SI
    return [r]


def s05_sfdr_art9_no_min() -> list[dict[str, str]]:
    r = clean_row()
    r["27"] = "9"  # SFDR Art-9 product
    r["31"] = ""   # blank → triggers EET-XF-ART9-MIN-LT
    r["45"] = ""   # blank → triggers EET-XF-ART9-MIN-ENV
    r["48"] = ""   # blank → triggers EET-XF-ART9-MIN-SOC
    # Switch the row out of Art-8: clear the Art-8 fields so we don't double up.
    r["40"] = "N"
    r["41"] = ""
    r["30"] = ""
    return [r]


SCENARIOS = [
    ("01_clean.xlsx",                s01_clean),
    ("02_missing_mandatory.xlsx",    s02_missing_mandatory),
    ("03_bad_formats.xlsx",          s03_bad_formats),
    ("04_sfdr_art8_no_min.xlsx",     s04_sfdr_art8_no_min),
    ("05_sfdr_art9_no_min.xlsx",     s05_sfdr_art9_no_min),
]


def write_readme() -> None:
    txt = (
        "# EET V1.1.3 example files\n\n"
        "Generated by `tools/build_eet_samples.py`. One clean reference plus\n"
        "four deliberately broken files exercising the EET rule set.\n\n"
        "| File | What it demonstrates |\n"
        "|------|----------------------|\n"
        "| `01_clean.xlsx` | All M-flagged fields populated; SFDR Art-8 product layout. |\n"
        "| `02_missing_mandatory.xlsx` | Blanks NUM=5, 7, 23, 25, 26 → PRESENCE/* errors. |\n"
        "| `03_bad_formats.xlsx` | Invalid ISO 8601 datetime / date, non-ISO-4217 currency, non-Y/N reporting flag. |\n"
        "| `04_sfdr_art8_no_min.xlsx` | SFDR Art-8 product without Art-8 minimum proportions → `EET-XF-ART8-MIN-LT`, `EET-XF-ART8-MIN-SI`. |\n"
        "| `05_sfdr_art9_no_min.xlsx` | SFDR Art-9 product without Art-9 minimum proportions → `EET-XF-ART9-MIN-LT`, `EET-XF-ART9-MIN-ENV`, `EET-XF-ART9-MIN-SOC`. |\n\n"
        "Open via `mvn javafx:run` → EET tab → *Browse…* or run `mvn -Dtest=EetExampleSamplesTest test`.\n"
    )
    (OUT / "README.md").write_text(txt, encoding="utf-8")
    print(f"Wrote {(OUT / 'README.md').relative_to(ROOT)}")


def main() -> int:
    write_scenarios(OUT, MANIFEST["sheetName"], HEADER_NUMS, HEADERS, SCENARIOS)
    write_readme()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
