"""Generate the EMT V4.3 sample fixtures into ``samples/emt/``.

Three files: clean, missing-mandatory, bad-formats. EMT has no SME-validated
cross-field rules in the current rule set, so XF-specific scenarios are
deliberately omitted.
"""
from __future__ import annotations

from pathlib import Path

from build_examples import make_isin
from findatex_realistic_values import (
    OVERRIDES_EMT, apply_overrides, share_classes,
)
from findatex_sample_helpers import (
    ROOT, FieldRow, load_spec, value_for, write_scenarios, write_xlsx,
)

OUT = ROOT / "samples" / "emt"
OUT.mkdir(parents=True, exist_ok=True)

MANIFEST, FIELDS = load_spec("EMT", "V4.3")

# Headers = every M-flagged field's path. EMT has 40 M fields so the
# resulting spreadsheet has 40 columns, which is enough to drive
# PresenceRule + FormatRule.
M_FIELDS: list[FieldRow] = [r for r in FIELDS if r.flag == "M"]
HEADER_NUMS = [r.num for r in M_FIELDS]
HEADERS = [r.path for r in M_FIELDS]
BY_NUM: dict[str, FieldRow] = {r.num: r for r in FIELDS}


def clean_row() -> dict[str, str]:
    return {n: value_for(BY_NUM[n].codif) for n in HEADER_NUMS}


def s00_showcase() -> list[dict[str, str]]:
    """25 share classes across four products — the file behind "Try an example".

    Same fund range as the EET and EPT showcases, so the three templates can be
    read side by side as one manufacturer's delivery. Values come from
    ``value_for`` first and are then overwritten with the curated ones, which
    keeps un-curated fields format-valid instead of blank.
    """
    rows: list[dict[str, str]] = []
    for sc in share_classes(make_isin):
        row = {n: value_for(BY_NUM[n].codif) for n in HEADER_NUMS}
        rows.append(apply_overrides(row, OVERRIDES_EMT, sc))
    for idx, cells in SHOWCASE_DEFECTS.items():
        for num, value in cells.items():
            if num in rows[idx]:
                rows[idx][num] = value
    return rows


# Row index → {num: value}. About one defect per three rows, spread across the
# rule families a reviewer would actually meet in a real delivery.
SHOWCASE_DEFECTS: dict[int, dict[str, str]] = {
    2:  {"15": "31/12/2025"},        # FORMAT/15 — dd/mm/yyyy instead of ISO 8601
    4:  {"12": "EuroX"},             # FORMAT/12 — not an ISO 4217 code
    7:  {"11": ""},                  # PRESENCE/11 — instrument name missing
    9:  {"5": "2026-13-40"},         # FORMAT/5  — impossible generation timestamp
    12: {"10": "42"},                # FORMAT/10 — outside the closed list {1..10, 99}
    15: {"55": "abc"},               # FORMAT/55 — holding period neither a number nor V/S/M/L/H
    18: {"71": "abc"},               # FORMAT/71 — ongoing cost is not numeric
    21: {"9": ""},                   # PRESENCE/9  — no instrument identifier
    23: {"79": ""},                  # PRESENCE/79 — ex-ante cost reference date missing
}


def s01_clean() -> list[dict[str, str]]:
    return [clean_row()]


def s02_missing_mandatory() -> list[dict[str, str]]:
    r = clean_row()
    # Blank five M fields → PRESENCE/* errors
    for n in ["5", "11", "12", "15", "16"]:
        if n in r:
            r[n] = ""
    return [r]


def s03_bad_formats() -> list[dict[str, str]]:
    r = clean_row()
    if "5" in r:    r["5"] = "31/12/2025 12:00"   # ISO 8601 datetime → wrong layout
    if "12" in r:   r["12"] = "EuroX"              # ISO 4217 → not a 3-letter code
    if "15" in r:   r["15"] = "2025-13-40"         # ISO 8601 date → impossible
    if "6" in r:    r["6"] = "Maybe"               # Y/N → invalid
    return [r]


SCENARIOS = [
    ("01_clean.xlsx",             s01_clean),
    ("02_missing_mandatory.xlsx", s02_missing_mandatory),
    ("03_bad_formats.xlsx",       s03_bad_formats),
]


def write_readme() -> None:
    txt = (
        "# EMT V4.3 example files\n\n"
        "Generated by `tools/build_emt_samples.py`. The showcase file is the demo\n"
        "behind *\"No file at hand? Try an example\"*; the numbered files are\n"
        "one-rule-family-each regression fixtures. EMT cross-field rules are not\n"
        "yet encoded (see `EmtRuleSet` TODO), so only mechanical rule families\n"
        "are exercised here.\n\n"
        "| File | What it demonstrates |\n"
        "|------|----------------------|\n"
        "| `00_showcase.xlsx` | **The demo file.** 25 share classes across four products (the same fund range as the EET and EPT showcases), with MiFID II target-market answers and ex-ante/ex-post cost blocks that vary by risk profile and share class. Nine curated defects: bad ISO dates, a non-ISO currency, an out-of-list code type, a holding period that is neither a number nor V/S/M/L/H, a non-numeric ongoing cost, and three missing mandatory cells. |\n"
        "| `01_clean.xlsx` | All 40 M-flagged fields populated. |\n"
        "| `02_missing_mandatory.xlsx` | Blanks NUM=5, 11, 12, 15, 16 → PRESENCE/* errors. |\n"
        "| `03_bad_formats.xlsx` | Invalid ISO 8601 datetime / date, non-ISO-4217 currency, non-Y/N reporting flag. |\n\n"
        "Open via `mvn javafx:run` → EMT tab → *Browse…* or run `mvn -Dtest=EmtExampleSamplesTest test`.\n"
    )
    (OUT / "README.md").write_text(txt, encoding="utf-8")
    print(f"Wrote {(OUT / 'README.md').relative_to(ROOT)}")


def main() -> int:
    write_xlsx(OUT / "00_showcase.xlsx", MANIFEST["sheetName"], HEADERS,
               [[r[n] for n in HEADER_NUMS] for r in s00_showcase()])
    write_scenarios(OUT, MANIFEST["sheetName"], HEADER_NUMS, HEADERS, SCENARIOS)
    write_readme()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
