"""Generate the EPT V2.1 sample fixtures into ``samples/ept/``.

Three files: clean, missing-mandatory, bad-formats. EPT has no
SME-validated cross-field rules in the current rule set; only mechanical
rule families are exercised here.
"""
from __future__ import annotations

from pathlib import Path

from build_examples import make_isin
from findatex_realistic_values import (
    OVERRIDES_EPT, apply_overrides, share_classes,
)
from findatex_sample_helpers import (
    ROOT, FieldRow, load_spec, value_for, write_scenarios, write_xlsx,
)

OUT = ROOT / "samples" / "ept"
OUT.mkdir(parents=True, exist_ok=True)

MANIFEST, FIELDS = load_spec("EPT", "V2.1")

M_FIELDS: list[FieldRow] = [r for r in FIELDS if r.flag == "M"]
HEADER_NUMS = [r.num for r in M_FIELDS]
HEADERS = [r.path for r in M_FIELDS]
BY_NUM: dict[str, FieldRow] = {r.num: r for r in FIELDS}


def clean_row() -> dict[str, str]:
    return {n: value_for(BY_NUM[n].codif) for n in HEADER_NUMS}


def s00_showcase() -> list[dict[str, str]]:
    """25 share classes across four products — the file behind "Try an example".

    Same fund range as the EET and EPT showcases, so the three templates can be
    read side by side as one manufacturer's delivery. Values come from
    ``value_for`` first and are then overwritten with the curated ones, which
    keeps un-curated fields format-valid instead of blank.
    """
    rows: list[dict[str, str]] = []
    for sc in share_classes(make_isin):
        row = {n: value_for(BY_NUM[n].codif) for n in HEADER_NUMS}
        rows.append(apply_overrides(row, OVERRIDES_EPT, sc))
    for idx, cells in SHOWCASE_DEFECTS.items():
        for num, value in cells.items():
            if num in rows[idx]:
                rows[idx][num] = value
    return rows


# Row index → {num: value}. About one defect per three rows, spread across the
# rule families a reviewer would actually meet in a real delivery.
SHOWCASE_DEFECTS: dict[int, dict[str, str]] = {
    2:  {"18": "28/11/2025"},        # FORMAT/18 — dd/mm/yyyy instead of ISO 8601
    5:  {"17": "EuroX"},             # FORMAT/17 — not an ISO 4217 code
    7:  {"16": ""},                  # PRESENCE/16 — portfolio name missing
    10: {"4": "2026-13-40"},         # FORMAT/4  — impossible generation timestamp
    13: {"38": "X"},                 # FORMAT/38 — liquidity risk outside {M, I, L}
    16: {"15": "42"},                # FORMAT/15 — outside the closed list {1..9, 99}
    19: {"75": "abc"},               # FORMAT/75 — ongoing cost is not numeric
    21: {"14": ""},                  # PRESENCE/14 — no portfolio identifier
    24: {"35": ""},                  # PRESENCE/35 — recommended holding period missing
}


def s01_clean() -> list[dict[str, str]]:
    return [clean_row()]


def s02_missing_mandatory() -> list[dict[str, str]]:
    r = clean_row()
    for n in ["4", "9", "16", "17", "18"]:
        if n in r:
            r[n] = ""
    return [r]


def s03_bad_formats() -> list[dict[str, str]]:
    r = clean_row()
    if "4"  in r: r["4"]  = "31/12/2025 12:00"   # ISO 8601 datetime → wrong layout
    if "17" in r: r["17"] = "EuroX"               # ISO 4217 → not a 3-letter code
    if "18" in r: r["18"] = "2025-13-40"          # ISO 8601 date → impossible
    if "5"  in r: r["5"]  = "Maybe"               # Y/N → invalid
    return [r]


SCENARIOS = [
    ("01_clean.xlsx",             s01_clean),
    ("02_missing_mandatory.xlsx", s02_missing_mandatory),
    ("03_bad_formats.xlsx",       s03_bad_formats),
]


def write_readme() -> None:
    txt = (
        "# EPT V2.1 example files\n\n"
        "Generated by `tools/build_ept_samples.py`. The showcase file is the demo\n"
        "behind *\"No file at hand? Try an example\"*; the numbered files are\n"
        "one-rule-family-each regression fixtures. EPT cross-field rules are not\n"
        "yet encoded (see `EptRuleSet` TODO), so only mechanical rule families\n"
        "are exercised here.\n\n"
        "| File | What it demonstrates |\n"
        "|------|----------------------|\n"
        "| `00_showcase.xlsx` | **The demo file.** 25 share classes across four products (the same fund range as the EET and EMT showcases), with PRIIPs KID data: SRI/MRM per risk profile, the four performance scenarios scaled to that risk, cost blocks and the narrative fields. Nine curated defects: bad ISO dates, a non-ISO currency, an out-of-list code type, a liquidity risk outside {M, I, L}, a non-numeric ongoing cost, and three missing mandatory cells. |\n"
        "| `01_clean.xlsx` | All 66 M-flagged fields populated. |\n"
        "| `02_missing_mandatory.xlsx` | Blanks NUM=4, 9, 16, 17, 18 → PRESENCE/* errors. |\n"
        "| `03_bad_formats.xlsx` | Invalid ISO 8601 datetime / date, non-ISO-4217 currency, non-Y/N reporting flag. |\n\n"
        "Open via `mvn javafx:run` → EPT tab → *Browse…* or run `mvn -Dtest=EptExampleSamplesTest test`.\n"
    )
    (OUT / "README.md").write_text(txt, encoding="utf-8")
    print(f"Wrote {(OUT / 'README.md').relative_to(ROOT)}")


def main() -> int:
    write_xlsx(OUT / "00_showcase.xlsx", MANIFEST["sheetName"], HEADERS,
               [[r[n] for n in HEADER_NUMS] for r in s00_showcase()])
    write_scenarios(OUT, MANIFEST["sheetName"], HEADER_NUMS, HEADERS, SCENARIOS)
    write_readme()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
