"""Generate the EPT V2.1 sample fixtures into ``samples/ept/``.

Three files: clean, missing-mandatory, bad-formats. EPT has no
SME-validated cross-field rules in the current rule set; only mechanical
rule families are exercised here.
"""
from __future__ import annotations

from pathlib import Path

from findatex_sample_helpers import (
    ROOT, FieldRow, load_spec, value_for, write_scenarios,
)

OUT = ROOT / "samples" / "ept"
OUT.mkdir(parents=True, exist_ok=True)

MANIFEST, FIELDS = load_spec("EPT", "V2.1")

M_FIELDS: list[FieldRow] = [r for r in FIELDS if r.flag == "M"]
HEADER_NUMS = [r.num for r in M_FIELDS]
HEADERS = [r.path for r in M_FIELDS]
BY_NUM: dict[str, FieldRow] = {r.num: r for r in FIELDS}


def clean_row() -> dict[str, str]:
    return {n: value_for(BY_NUM[n].codif) for n in HEADER_NUMS}


def s01_clean() -> list[dict[str, str]]:
    return [clean_row()]


def s02_missing_mandatory() -> list[dict[str, str]]:
    r = clean_row()
    for n in ["4", "9", "16", "17", "18"]:
        if n in r:
            r[n] = ""
    return [r]


def s03_bad_formats() -> list[dict[str, str]]:
    r = clean_row()
    if "4"  in r: r["4"]  = "31/12/2025 12:00"   # ISO 8601 datetime → wrong layout
    if "17" in r: r["17"] = "EuroX"               # ISO 4217 → not a 3-letter code
    if "18" in r: r["18"] = "2025-13-40"          # ISO 8601 date → impossible
    if "5"  in r: r["5"]  = "Maybe"               # Y/N → invalid
    return [r]


SCENARIOS = [
    ("01_clean.xlsx",             s01_clean),
    ("02_missing_mandatory.xlsx", s02_missing_mandatory),
    ("03_bad_formats.xlsx",       s03_bad_formats),
]


def write_readme() -> None:
    txt = (
        "# EPT V2.1 example files\n\n"
        "Generated by `tools/build_ept_samples.py`. One clean reference plus\n"
        "two deliberately broken files. EPT cross-field rules are not yet\n"
        "encoded (see `EptRuleSet` TODO), so only mechanical rule families\n"
        "are exercised here.\n\n"
        "| File | What it demonstrates |\n"
        "|------|----------------------|\n"
        "| `01_clean.xlsx` | All 66 M-flagged fields populated. |\n"
        "| `02_missing_mandatory.xlsx` | Blanks NUM=4, 9, 16, 17, 18 → PRESENCE/* errors. |\n"
        "| `03_bad_formats.xlsx` | Invalid ISO 8601 datetime / date, non-ISO-4217 currency, non-Y/N reporting flag. |\n\n"
        "Open via `mvn javafx:run` → EPT tab → *Browse…* or run `mvn -Dtest=EptExampleSamplesTest test`.\n"
    )
    (OUT / "README.md").write_text(txt, encoding="utf-8")
    print(f"Wrote {(OUT / 'README.md').relative_to(ROOT)}")


def main() -> int:
    write_scenarios(OUT, MANIFEST["sheetName"], HEADER_NUMS, HEADERS, SCENARIOS)
    write_readme()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
