"""Generate the EMT V4.3 sample fixtures into ``samples/emt/``.

Three files: clean, missing-mandatory, bad-formats. EMT has no SME-validated
cross-field rules in the current rule set, so XF-specific scenarios are
deliberately omitted.
"""
from __future__ import annotations

from pathlib import Path

from findatex_sample_helpers import (
    ROOT, FieldRow, load_spec, value_for, write_scenarios,
)

OUT = ROOT / "samples" / "emt"
OUT.mkdir(parents=True, exist_ok=True)

MANIFEST, FIELDS = load_spec("EMT", "V4.3")

# Headers = every M-flagged field's path. EMT has 40 M fields so the
# resulting spreadsheet has 40 columns, which is enough to drive
# PresenceRule + FormatRule.
M_FIELDS: list[FieldRow] = [r for r in FIELDS if r.flag == "M"]
HEADER_NUMS = [r.num for r in M_FIELDS]
HEADERS = [r.path for r in M_FIELDS]
BY_NUM: dict[str, FieldRow] = {r.num: r for r in FIELDS}


def clean_row() -> dict[str, str]:
    return {n: value_for(BY_NUM[n].codif) for n in HEADER_NUMS}


def s01_clean() -> list[dict[str, str]]:
    return [clean_row()]


def s02_missing_mandatory() -> list[dict[str, str]]:
    r = clean_row()
    # Blank five M fields → PRESENCE/* errors
    for n in ["5", "11", "12", "15", "16"]:
        if n in r:
            r[n] = ""
    return [r]


def s03_bad_formats() -> list[dict[str, str]]:
    r = clean_row()
    if "5" in r:    r["5"] = "31/12/2025 12:00"   # ISO 8601 datetime → wrong layout
    if "12" in r:   r["12"] = "EuroX"              # ISO 4217 → not a 3-letter code
    if "15" in r:   r["15"] = "2025-13-40"         # ISO 8601 date → impossible
    if "6" in r:    r["6"] = "Maybe"               # Y/N → invalid
    return [r]


SCENARIOS = [
    ("01_clean.xlsx",             s01_clean),
    ("02_missing_mandatory.xlsx", s02_missing_mandatory),
    ("03_bad_formats.xlsx",       s03_bad_formats),
]


def write_readme() -> None:
    txt = (
        "# EMT V4.3 example files\n\n"
        "Generated by `tools/build_emt_samples.py`. One clean reference plus\n"
        "two deliberately broken files. EMT cross-field rules are not yet\n"
        "encoded (see `EmtRuleSet` TODO), so only mechanical rule families\n"
        "are exercised here.\n\n"
        "| File | What it demonstrates |\n"
        "|------|----------------------|\n"
        "| `01_clean.xlsx` | All 40 M-flagged fields populated. |\n"
        "| `02_missing_mandatory.xlsx` | Blanks NUM=5, 11, 12, 15, 16 → PRESENCE/* errors. |\n"
        "| `03_bad_formats.xlsx` | Invalid ISO 8601 datetime / date, non-ISO-4217 currency, non-Y/N reporting flag. |\n\n"
        "Open via `mvn javafx:run` → EMT tab → *Browse…* or run `mvn -Dtest=EmtExampleSamplesTest test`.\n"
    )
    (OUT / "README.md").write_text(txt, encoding="utf-8")
    print(f"Wrote {(OUT / 'README.md').relative_to(ROOT)}")


def main() -> int:
    write_scenarios(OUT, MANIFEST["sheetName"], HEADER_NUMS, HEADERS, SCENARIOS)
    write_readme()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
