package com.findatex.validator.web.api;

import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.InternalServerErrorException;
import jakarta.ws.rs.NotFoundException;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * Serves the canonical end-user help document plus the per-template validation rules reference
 * generated by {@code com.findatex.validator.docs.RuleDocGenerator}. All Markdown sources live
 * on the classpath under {@code /help/} and are read once at startup.
 */
@ApplicationScoped
@Path("/api/help")
public class HelpResource {

    private static final String HELP_RESOURCE = "/help/HELP.md";
    private static final String RULES_INDEX_RESOURCE = "/help/rules/index.json";
    private static final String RULES_DIR_RESOURCE = "/help/rules/";
    private static final Pattern SLUG = Pattern.compile("[a-z0-9][a-z0-9-]{0,80}");

    private String body;
    private String rulesIndexJson = "[]";
    private final Map<String, String> rulesBySlug = new LinkedHashMap<>();

    @PostConstruct
    void load() {
        try (InputStream in = HelpResource.class.getResourceAsStream(HELP_RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException("Missing classpath resource " + HELP_RESOURCE);
            }
            body = new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new IllegalStateException("Could not read " + HELP_RESOURCE, e);
        }

        try (InputStream in = HelpResource.class.getResourceAsStream(RULES_INDEX_RESOURCE)) {
            if (in != null) {
                rulesIndexJson = new String(in.readAllBytes(), StandardCharsets.UTF_8);
                for (String slug : extractSlugs(rulesIndexJson)) {
                    String md = readClasspath(RULES_DIR_RESOURCE + slug + ".md");
                    if (md != null) rulesBySlug.put(slug, md);
                }
            }
        } catch (IOException e) {
            throw new IllegalStateException("Could not read " + RULES_INDEX_RESOURCE, e);
        }
    }

    @GET
    @Produces("text/markdown; charset=utf-8")
    public Response get() {
        if (body == null) throw new InternalServerErrorException("Help content not loaded");
        return Response.ok(body)
                .header("Cache-Control", "public, max-age=3600")
                .build();
    }

    @GET
    @jakarta.ws.rs.Path("/rules")
    @Produces(MediaType.APPLICATION_JSON)
    public Response rulesIndex() {
        return Response.ok(rulesIndexJson)
                .header("Cache-Control", "public, max-age=3600")
                .build();
    }

    @GET
    @jakarta.ws.rs.Path("/rules/{slug}")
    @Produces("text/markdown; charset=utf-8")
    public Response ruleDoc(@PathParam("slug") String slug) {
        if (slug == null || !SLUG.matcher(slug).matches()) {
            throw new NotFoundException();
        }
        String md = rulesBySlug.get(slug);
        if (md == null) throw new NotFoundException();
        return Response.ok(md)
                .header("Cache-Control", "public, max-age=3600")
                .build();
    }

    private static String readClasspath(String resource) {
        try (InputStream in = HelpResource.class.getResourceAsStream(resource)) {
            if (in == null) return null;
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            return null;
        }
    }

    /**
     * Extract {@code "slug": "<value>"} occurrences from the index JSON without pulling in a
     * JSON parser dependency on the web layer (Jackson is available via Quarkus, but this
     * trivially-shaped file does not warrant it).
     */
    static java.util.List<String> extractSlugs(String json) {
        java.util.List<String> out = new java.util.ArrayList<>();
        Pattern p = Pattern.compile("\"slug\"\\s*:\\s*\"([^\"]+)\"");
        java.util.regex.Matcher m = p.matcher(json);
        while (m.find()) out.add(m.group(1));
        return out;
    }
}
