package com.findatex.validator.report;

import com.findatex.validator.AppInfo;
import com.findatex.validator.domain.FundGroup;
import com.findatex.validator.domain.FundGrouper;
import com.findatex.validator.domain.TptRow;
import com.findatex.validator.spec.FieldSpec;
import com.findatex.validator.spec.SpecCatalog;
import com.findatex.validator.template.api.ProfileKey;
import com.findatex.validator.template.api.ProfileSet;
import com.findatex.validator.template.api.TemplateVersion;
import com.findatex.validator.validation.Finding;
import com.findatex.validator.validation.FindingContext;
import com.findatex.validator.validation.Severity;
import org.apache.poi.ooxml.POIXMLProperties;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Date;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

public final class XlsxReportWriter {

    static final int REPORT_SCHEMA_VERSION = 1;
    static final String GITHUB_URL = "https://github.com/karlkauc/findatex-validator";

    private final SpecCatalog catalog;
    private final ProfileSet profileSet;
    private final TemplateVersion templateVersion;
    private final GenerationUi generationUi;

    public XlsxReportWriter(SpecCatalog catalog,
                            ProfileSet profileSet,
                            TemplateVersion templateVersion,
                            GenerationUi generationUi) {
        this.catalog = java.util.Objects.requireNonNull(catalog, "catalog");
        this.profileSet = java.util.Objects.requireNonNull(profileSet, "profileSet");
        this.templateVersion = java.util.Objects.requireNonNull(templateVersion, "templateVersion");
        this.generationUi = java.util.Objects.requireNonNull(generationUi, "generationUi");
    }

    public void write(QualityReport report, Path out) throws IOException {
        try (XSSFWorkbook wb = new XSSFWorkbook();
             OutputStream os = Files.newOutputStream(out)) {
            CellStyle header = XlsxStyles.headerStyle(wb);
            CellStyle pct = XlsxStyles.percentStyle(wb);
            CellStyle err = XlsxStyles.colourStyle(wb, IndexedColors.ROSE.getIndex());
            CellStyle warn = XlsxStyles.colourStyle(wb, IndexedColors.LIGHT_YELLOW.getIndex());
            CellStyle ok = XlsxStyles.colourStyle(wb, IndexedColors.LIGHT_GREEN.getIndex());
            CellStyle info = XlsxStyles.colourStyle(wb, IndexedColors.PALE_BLUE.getIndex());

            applyWorkbookProperties(wb, report);
            writeSummary(wb, report, header, pct);
            writeScores(wb, report, header, pct);
            writeFindings(wb, report, header, err, warn);
            writeFieldCoverage(wb, report, header);
            writePerPosition(wb, report, header, ok, warn, err);
            writeAnnotatedSource(wb, report, header, err, warn, info);

            wb.write(os);
        }
    }

    private void applyWorkbookProperties(XSSFWorkbook wb, QualityReport r) {
        Map<Severity, Long> bySeverity = findingsBySeverity(r);
        long errors = bySeverity.getOrDefault(Severity.ERROR, 0L);
        long warnings = bySeverity.getOrDefault(Severity.WARNING, 0L);
        long infos = bySeverity.getOrDefault(Severity.INFO, 0L);
        double overallScore = r.scores().getOrDefault(ScoreCategory.OVERALL, 0.0);
        double overallPct = Math.round(overallScore * 1000.0) / 10.0;
        String creator = AppInfo.applicationWithVersion();
        String sourceFilename = sourceFilename(r);
        String profileCodes = r.activeProfiles().stream()
                .map(ProfileKey::code)
                .collect(Collectors.joining(", "));
        String reportTitle = AppInfo.applicationName() + " – " + templateVersion.label() + " Quality Report";
        String description = "Quality report generated by " + creator
                + ". Template: " + templateVersion.label()
                + ". Profiles: " + (profileCodes.isEmpty() ? "(none)" : profileCodes)
                + ". Findings: " + r.findings().size()
                + " (" + errors + " errors, " + warnings + " warnings, " + infos + " info)"
                + ". Overall score: " + overallPct + "%.";

        POIXMLProperties props = wb.getProperties();
        POIXMLProperties.CoreProperties core = props.getCoreProperties();
        core.setTitle(reportTitle);
        core.setCreator(creator);
        core.setLastModifiedByUser(creator);
        core.setSubjectProperty("Validation report for " + sourceFilename);
        core.setDescription(description);
        core.setKeywords("FinDatEx, " + templateVersion.templateId().name() + ", validation, quality report");
        core.setCategory("Validation Report");
        Date generated = Date.from(r.generatedAt());
        core.setCreated(Optional.of(generated));
        core.setModified(Optional.of(generated));

        POIXMLProperties.ExtendedProperties ext = props.getExtendedProperties();
        ext.setApplication(AppInfo.applicationName());
        ext.setAppVersion(AppInfo.version());

        POIXMLProperties.CustomProperties custom = props.getCustomProperties();
        custom.addProperty("FinDatEx-Validator-Version", AppInfo.version());
        custom.addProperty("FinDatEx-Validator-Build-Timestamp", AppInfo.buildTimestamp());
        custom.addProperty("FinDatEx-Report-Schema-Version", REPORT_SCHEMA_VERSION);
        custom.addProperty("Template-Id", templateVersion.templateId().name());
        custom.addProperty("Template-Version", templateVersion.version());
        custom.addProperty("Template-Label", templateVersion.label());
        if (templateVersion.releaseDate() != null) {
            custom.addProperty("Template-Release-Date", templateVersion.releaseDate().toString());
        }
        custom.addProperty("Source-Filename", sourceFilename);
        custom.addProperty("Source-Format", nz(r.file().inputFormat()));
        custom.addProperty("Source-Row-Count", r.file().rows().size());
        custom.addProperty("Active-Profiles", profileCodes);
        custom.addProperty("Findings-Total", r.findings().size());
        custom.addProperty("Findings-Errors", (int) errors);
        custom.addProperty("Findings-Warnings", (int) warnings);
        custom.addProperty("Findings-Info", (int) infos);
        custom.addProperty("Quality-Score-Total", overallPct);
        custom.addProperty("Generated-At-UTC", r.generatedAt().toString());
        custom.addProperty("Generation-UI", generationUi.label());
    }

    private static Map<Severity, Long> findingsBySeverity(QualityReport r) {
        Map<Severity, Long> m = new EnumMap<>(Severity.class);
        for (Finding f : r.findings()) {
            m.merge(f.severity(), 1L, Long::sum);
        }
        return m;
    }

    private static String sourceFilename(QualityReport r) {
        Path source = r.file().source();
        if (source == null) return "(unknown)";
        Path name = source.getFileName();
        return name == null ? source.toString() : name.toString();
    }

    private void writeSummary(Workbook wb, QualityReport r, CellStyle header, CellStyle pct) {
        Sheet s = wb.createSheet("Summary");
        int row = 0;
        XlsxStyles.addRow(s, row++, header, templateVersion.label() + " Quality Report");
        XlsxStyles.addRow(s, row++, null,   "Produced by " + AppInfo.applicationWithVersion());
        XlsxStyles.addRow(s, row++, null,   GITHUB_URL);
        XlsxStyles.addRow(s, row++, null,   "");
        XlsxStyles.addRow(s, row++, null,   "Source file",      r.file().source().toString());
        XlsxStyles.addRow(s, row++, null,   "Format",           r.file().inputFormat());
        XlsxStyles.addRow(s, row++, null,   "Generated",        r.generatedAt().toString());
        XlsxStyles.addRow(s, row++, null,   "Rows",             Integer.toString(r.file().rows().size()));
        XlsxStyles.addRow(s, row++, null,   "Mapped fields",    Integer.toString(r.file().headerToNumKey().size()));
        XlsxStyles.addRow(s, row++, null,   "Unmapped headers", String.join(", ", r.file().unmappedHeaders()));
        XlsxStyles.addRow(s, row++, null,   "Active profiles",
                r.activeProfiles().stream().map(ProfileKey::displayName).collect(Collectors.joining(", ")));
        row++;
        XlsxStyles.addRow(s, row++, header, "Findings by severity");
        Map<Severity, Long> bySeverity = findingsBySeverity(r);
        XlsxStyles.addRow(s, row++, null, "ERROR",   Long.toString(bySeverity.getOrDefault(Severity.ERROR,   0L)));
        XlsxStyles.addRow(s, row++, null, "WARNING", Long.toString(bySeverity.getOrDefault(Severity.WARNING, 0L)));
        XlsxStyles.addRow(s, row++, null, "INFO",    Long.toString(bySeverity.getOrDefault(Severity.INFO,    0L)));
        row++;
        XlsxStyles.addRow(s, row++, header, "Report metadata");
        String releaseSuffix = templateVersion.releaseDate() == null
                ? ""
                : " (released " + templateVersion.releaseDate() + ")";
        XlsxStyles.addRow(s, row++, null, "Template",          templateVersion.label() + releaseSuffix);
        XlsxStyles.addRow(s, row++, null, "Validator version", AppInfo.version() + "  (build " + AppInfo.buildTimestamp() + ")");
        XlsxStyles.addRow(s, row++, null, "Generation UI",     generationUi.label());
        for (int c = 0; c < 3; c++) s.autoSizeColumn(c);
    }

    private static void writeScores(Workbook wb, QualityReport r, CellStyle header, CellStyle pct) {
        Sheet s = wb.createSheet("Scores");
        int row = 0;
        XlsxStyles.addRow(s, row++, header, "Category", "Score");
        for (Map.Entry<ScoreCategory, Double> e : r.scores().entrySet()) {
            Row rr = s.createRow(row++);
            rr.createCell(0).setCellValue(e.getKey().name());
            org.apache.poi.ss.usermodel.Cell c = rr.createCell(1);
            c.setCellValue(e.getValue());
            c.setCellStyle(pct);
        }
        row++;
        XlsxStyles.addRow(s, row++, header, "Per-profile scores");
        XlsxStyles.addRow(s, row++, header, "Profile", "Category", "Score");
        for (Map.Entry<ProfileKey, Map<ScoreCategory, Double>> pe : r.perProfileScores().entrySet()) {
            for (Map.Entry<ScoreCategory, Double> ce : pe.getValue().entrySet()) {
                Row rr = s.createRow(row++);
                rr.createCell(0).setCellValue(pe.getKey().displayName());
                rr.createCell(1).setCellValue(ce.getKey().name());
                org.apache.poi.ss.usermodel.Cell v = rr.createCell(2);
                v.setCellValue(ce.getValue());
                v.setCellStyle(pct);
            }
        }
        for (int c = 0; c < 4; c++) s.autoSizeColumn(c);
    }

    private static void writeFindings(Workbook wb, QualityReport r,
                                      CellStyle header, CellStyle err, CellStyle warn) {
        Sheet s = wb.createSheet("Findings");
        int row = 0;
        XlsxStyles.addRow(s, row++, header,
                "Severity", "Profile", "Rule",
                "Fund ID", "Fund name", "Valuation date",
                "Field#", "Field name", "Row", "Instrument code", "Instrument name",
                "Weight", "Value", "Message");
        for (Finding f : r.findings()) {
            Row rr = s.createRow(row++);
            CellStyle style = switch (f.severity()) {
                case ERROR -> err;
                case WARNING -> warn;
                case INFO -> null;
            };
            FindingContext ctx = f.context() == null ? FindingContext.EMPTY : f.context();

            org.apache.poi.ss.usermodel.Cell c0 = rr.createCell(0);
            c0.setCellValue(f.severity().name());
            if (style != null) c0.setCellStyle(style);
            rr.createCell(1).setCellValue(f.profile() == null ? "" : f.profile().displayName());
            rr.createCell(2).setCellValue(f.ruleId());
            rr.createCell(3).setCellValue(nz(ctx.portfolioId()));
            rr.createCell(4).setCellValue(nz(ctx.portfolioName()));
            rr.createCell(5).setCellValue(nz(ctx.valuationDate()));
            rr.createCell(6).setCellValue(nz(f.fieldNum()));
            rr.createCell(7).setCellValue(nz(f.fieldName()));
            rr.createCell(8).setCellValue(f.rowIndex() == null ? "" : f.rowIndex().toString());
            rr.createCell(9).setCellValue(nz(ctx.instrumentCode()));
            rr.createCell(10).setCellValue(nz(ctx.instrumentName()));
            rr.createCell(11).setCellValue(nz(ctx.valuationWeight()));
            rr.createCell(12).setCellValue(nz(f.value()));
            rr.createCell(13).setCellValue(nz(f.message()));
        }
        s.createFreezePane(3, 1);
        for (int c = 0; c < 14; c++) s.autoSizeColumn(c);
    }

    private static String nz(String s) { return s == null ? "" : s; }

    private void writeFieldCoverage(Workbook wb, QualityReport r, CellStyle header) {
        Sheet s = wb.createSheet("Field Coverage");
        int row = 0;
        java.util.List<ProfileKey> profiles = profileSet.all();
        java.util.List<String> headers = new java.util.ArrayList<>();
        headers.add("Field#");
        headers.add("NUM_DATA");
        headers.add("FunDataXML path");
        for (ProfileKey p : profiles) headers.add(p.displayName());
        headers.add("Present");
        headers.add("Missing");
        headers.add("Invalid");
        XlsxStyles.addRow(s, row++, header, headers.toArray(new String[0]));

        Map<String, long[]> byField = new HashMap<>(); // numKey -> [present, missing, invalid]
        for (FieldSpec spec : catalog.fields()) byField.put(spec.numKey(), new long[3]);

        for (TptRow tr : r.file().rows()) {
            for (Map.Entry<String, com.findatex.validator.domain.RawCell> e : tr.all().entrySet()) {
                long[] arr = byField.get(e.getKey());
                if (arr == null) continue;
                if (e.getValue().isEmpty()) arr[1]++;
                else arr[0]++;
            }
        }
        for (Finding f : r.findings()) {
            if (f.fieldNum() == null || f.severity() != Severity.ERROR) continue;
            if (f.ruleId().startsWith("FORMAT/")) {
                long[] arr = byField.get(f.fieldNum());
                if (arr != null) arr[2]++;
            }
        }
        for (FieldSpec spec : catalog.fields()) {
            long[] c = byField.get(spec.numKey());
            Row rr = s.createRow(row++);
            int col = 0;
            rr.createCell(col++).setCellValue(spec.numKey());
            rr.createCell(col++).setCellValue(spec.numData());
            rr.createCell(col++).setCellValue(spec.fundXmlPath() == null ? "" : spec.fundXmlPath());
            for (ProfileKey p : profiles) {
                rr.createCell(col++).setCellValue(spec.flag(p).name());
            }
            rr.createCell(col++).setCellValue(c == null ? 0 : c[0]);
            rr.createCell(col++).setCellValue(c == null ? 0 : c[1]);
            rr.createCell(col++).setCellValue(c == null ? 0 : c[2]);
        }
        s.createFreezePane(2, 1);
        int totalCols = 3 + profiles.size() + 3;
        for (int c = 0; c < totalCols; c++) s.autoSizeColumn(c);
    }

    private static void writePerPosition(Workbook wb, QualityReport r,
                                         CellStyle header, CellStyle ok, CellStyle warn, CellStyle err) {
        Sheet s = wb.createSheet("Per Position");
        // Per-position summary: row index + count of errors/warnings on that row.
        Map<Integer, long[]> byRow = new HashMap<>();
        for (Finding f : r.findings()) {
            if (f.rowIndex() == null) continue;
            long[] arr = byRow.computeIfAbsent(f.rowIndex(), k -> new long[2]);
            if (f.severity() == Severity.ERROR) arr[0]++;
            else if (f.severity() == Severity.WARNING) arr[1]++;
        }
        int row = 0;
        XlsxStyles.addRow(s, row++, header, "Row", "Errors", "Warnings", "Status");
        java.util.List<FundGroup> groups = FundGrouper.group(r.file());
        boolean multi = groups.size() > 1;
        for (FundGroup g : groups) {
            if (multi) {
                String pid = g.key().portfolioId() == null ? "(unknown)" : g.key().portfolioId();
                String pname = firstNonEmpty(g, "3");
                Row hr = s.createRow(row++);
                org.apache.poi.ss.usermodel.Cell hc = hr.createCell(0);
                hc.setCellValue("Fund: " + pid + (pname == null ? "" : " — " + pname));
                hc.setCellStyle(header);
            }
            for (TptRow tr : g.rows()) {
                long[] arr = byRow.getOrDefault(tr.rowIndex(), new long[2]);
                Row rr = s.createRow(row++);
                rr.createCell(0).setCellValue(tr.rowIndex());
                rr.createCell(1).setCellValue(arr[0]);
                rr.createCell(2).setCellValue(arr[1]);
                org.apache.poi.ss.usermodel.Cell status = rr.createCell(3);
                if (arr[0] > 0) {
                    status.setCellValue("ERROR");
                    status.setCellStyle(err);
                } else if (arr[1] > 0) {
                    status.setCellValue("WARNING");
                    status.setCellStyle(warn);
                } else {
                    status.setCellValue("OK");
                    status.setCellStyle(ok);
                }
            }
        }
        s.createFreezePane(0, 1);
        for (int c = 0; c < 4; c++) s.autoSizeColumn(c);
    }

    private static String firstNonEmpty(FundGroup g, String numKey) {
        for (TptRow r : g.rows()) {
            String v = r.stringValue(numKey).orElse(null);
            if (v != null && !v.isEmpty()) return v;
        }
        return null;
    }

    private static void writeAnnotatedSource(Workbook wb, QualityReport r,
                                             CellStyle headerStyle,
                                             CellStyle err, CellStyle warn, CellStyle info) {
        Sheet s = wb.createSheet("Annotated Source");
        AnnotatedSourceSheetWriter.write(s, r, headerStyle, err, warn, info);
    }
}
